talia = ["zielony_organ",    
         "zielony_lek",    
         "zielony_wirus",    
         "czerwony_organ",    
         "czerwony_lek",    
         "czerwony_wirus",    
         "niebieski_organ",    
         "niebieski_lek",    
         "niebieski_wirus",    
         "żółty_organ",    
         "żółty_lek",    
         "żółty_wirus",    
         "wielokolorowy_organ",    
         "wielokolorowy_lek",    
         "wielokolorowy_wirus"]
